version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - amazon-linux-extras install -y java-openjdk17
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk.x86_64
      - echo "Installing Maven..."
      - wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.5/apache-maven-3.9.5-bin.tar.gz
      - tar -xvzf apache-maven-3.9.5-bin.tar.gz
      - sudo mv apache-maven-3.9.5 /opt/maven
      - sudo ln -s /opt/maven/bin/mvn /usr/local/bin/mvn
      - mvn -version
  build:
    commands:
      - echo "Building the Java application with Maven..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar
  name: target-jar-file
  discard-paths: yes
